title: London Team Scripting & CI
author: Rawes82
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site has been setup to improve intra-team collaboration for scripting and CI activities

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
